server:
  port: 8080

spring:
  profiles:
    default: local

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  admin:
    username: admin
    password: admin1234

logging:
  level:
    org.hibernate.SQL: info
