-- V1__init.sql 테이블들에 컬럼 코멘트 추가

-- site_layout 테이블
ALTER TABLE site_layout
MODIFY COLUMN lang VARCHAR(2) NOT NULL COMMENT '언어 코드 (ko, en)',
MODIFY COLUMN header_html LONGTEXT NOT NULL COMMENT '헤더 HTML',
MODIFY COLUMN footer_html LONGTEXT NOT NULL COMMENT '푸터 HTML',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시';

-- site_menu 테이블
ALTER TABLE site_menu
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '메뉴 ID',
MODIFY COLUMN lang VARCHAR(2) NOT NULL COMMENT '언어 코드 (ko, en)',
MODIFY COLUMN menu_type VARCHAR(10) NOT NULL DEFAULT 'public' COMMENT '메뉴 타입 (public: 사용자메뉴, admin: 관리자메뉴)',
MODIFY COLUMN parent_id BIGINT NULL COMMENT '상위 메뉴 ID (NULL이면 1뎁스)',
MODIFY COLUMN label VARCHAR(64) NOT NULL COMMENT '메뉴 라벨',
MODIFY COLUMN href VARCHAR(255) NOT NULL COMMENT '링크 URL',
MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';

-- site_banner 테이블
ALTER TABLE site_banner
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '배너 ID',
MODIFY COLUMN lang VARCHAR(2) NOT NULL COMMENT '언어 코드 (ko, en)',
MODIFY COLUMN title VARCHAR(128) NOT NULL DEFAULT '' COMMENT '배너 제목',
MODIFY COLUMN type VARCHAR(16) NOT NULL COMMENT '배너 타입 (image, video, youtube)',
MODIFY COLUMN image_url VARCHAR(1024) NULL COMMENT '이미지 URL',
MODIFY COLUMN youtube_url VARCHAR(1024) NULL COMMENT '유튜브 URL',
MODIFY COLUMN link_url VARCHAR(1024) NULL COMMENT '클릭 시 이동 URL',
MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';

-- V3__add_cms_tables.sql 테이블들 (이미 코멘트 있지만 누락된 컬럼 추가)

-- content_page 테이블 (누락 컬럼)
ALTER TABLE content_page
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '페이지 ID',
MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';

-- board_category 테이블 (누락 컬럼)
ALTER TABLE board_category
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID',
MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';

-- board_post 테이블 (누락 컬럼)
ALTER TABLE board_post
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글 ID',
MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시';

-- attach_file 테이블 (이미 모든 컬럼에 코멘트 있음)
